project_id: '512984'
api_token_env: CROWDIN_PERSONAL_TOKEN
pull_request_title: "chore(i18n-crowdin): new crowdin translation \UF09F8C90"
commit_message: 'chore(i18n-crowdin): new translations for %original_file_name% (%language%)'
append_commit_message: 
files:
  - source: /src/locales/en-US/**/*.json
    translation: /src/locales/%locale%/**/%original_file_name%
