name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
      - 'package.json'

jobs:
  PublishNekokai:
    name: Publish Nekokai image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Nekokai Docker image
        uses: docker/build-push-action@v3.3.1
        with:
          push: true
          context: .
          tags: ghcr.io/skyra-project/nekokai:latest
